### ISSUE TITLE
Python WARC libraries can not read WARC files

### ISSUE THREAD

**Issue by maturban** [N0taN3rd/controlChromeHeadless#1]
Common Python libraries (e.g., [warc](http://warc.readthedocs.io/en/latest/) and [warcat](https://github.com/chfoo/warcat) ) that can handle WARC files failed to read WARC records/files: here is the error:

```    for record in f:
  File "/usr/local/lib/python2.7/site-packages/warc/warc.py", line 393, in __iter__
    record = self.read_record()
  File "/usr/local/lib/python2.7/site-packages/warc/warc.py", line 364, in read_record
    self.finish_reading_current_record()
  File "/usr/local/lib/python2.7/site-packages/warc/warc.py", line 360, in finish_reading_current_record
    self.expect(self.current_payload.fileobj, "\r\n")
  File "/usr/local/lib/python2.7/site-packages/warc/warc.py", line 352, in expect
    raise IOError(message)
IOError: Expected '\r\n', found 'WARC/1.0\r\n' 
```

- I think the issue is related to how the content-length is set plus the separator '\r\n\r\n'. Here is one of the WARC files for testing [index.warc.zip](https://github.com/N0taN3rd/controlChromeHeadless/files/1023092/index.warc.zip).
- No errors when reading WARCs generated by WARCreate

**Comment by N0taN3rd** [comment]
@maturban I am unable to reproduce that error using [pywb](https://github.com/ikreymer/pywb)'s cdx-indexer or [warcio](https://github.com/webrecorder/warcio)

![indexwarcdidindex](https://cloud.githubusercontent.com/assets/8648317/26374072/00558dc2-3fd2-11e7-890d-8d754affd6ed.png)

I was able to create a collection using pywb's [wb-manager](https://github.com/ikreymer/pywb/wiki/Auto-Configuration-and-Web-Archive-Collections-Manager) and added it to the collection (copied warc to /archive and indexed it successfully to /indexes) 

![replayingindexwarc](https://cloud.githubusercontent.com/assets/8648317/26374375/25b1c346-3fd3-11e7-8b79-d28f16c64c36.png)

Please let me know if the [index.cdxj.zip](https://github.com/N0taN3rd/controlChromeHeadless/files/1023630/index.cdxj.zip) is correct. 

I touched up WARCreates [warc generator](https://github.com/machawk1/warcreate/blob/2016rebase/js/warcGenerator.js) for the latest release. 
If you are using the latest release then it is using the browser version of the warc generation scheme used to generate that WARC and is the one used by WAIL but more industrial strength.

**Comment by maturban** [comment]
Thanks for pointing to [wario](https://github.com/webrecorder/warcio). It works now, and the WARC file is read correctly. You may close this issue.

**Comment by rjoberon** [comment]
Just as a remark in case someone else stumbles upon this issue when searching for the above-mentioned error message: A similar error can happen with warc-extractor.py from [ArchiveTools](https://github.com/recrm/ArchiveTools) when using it on compressed WARCs where the whole WARC file was compressed and not individually compressed WARC records concatenated: 
```
> ./warc-extractor.py -output_path out -dump content
parsing file.warc.gz
Traceback (most recent call last):
  File "./warc-extractor.py", line 828, in <module>
    parse(args)
  File "./warc-extractor.py", line 701, in parse
    for record in warc_records(args.string, args.path):
  File "./warc-extractor.py", line 675, in warc_records
    for record in warc_file:
  File "./warc-extractor.py", line 625, in __iter__
    record = self.read_record()
  File "./warc-extractor.py", line 602, in read_record
    self.finish_reading_current_record()
  File "./warc-extractor.py", line 597, in finish_reading_current_record
    self.expect(self.current_payload.fileobj, "\r\n")
  File "./warc-extractor.py", line 590, in expect
    raise IOError(message)
OSError: Expected '\r\n', found 'WARC/1.0\r\n'
```
(This WARC file was created using ArchiveFileExtractor from [ia-hadoop-tools](https://github.com/internetarchive/ia-hadoop-tools).)

Using [warcio](https://github.com/webrecorder/warcio) we can recompress the file:
```
warcio recompress file.warc.gz file_recompressed.warc.gz
```
and then use [ArchiveTools](https://github.com/recrm/ArchiveTools) to extract the files from the individual records:

```shell
./warc-extractor.py -output_path out -dump content
```
HTH
