### ISSUE TITLE
WARC records with 3xx status code are missing

### ISSUE THREAD

**Issue by maturban** [N0taN3rd/controlChromeHeadless#2]
I used [webrecorder.io](webrecorder.io) to generate .warc file for [reuters](	
http://www.reuters.com/news). Looking in this [.warc](https://github.com/N0taN3rd/controlChromeHeadless/files/1026750/testfast-20170524184852.warc.gz), I can see all (at least 37) 3xx WARC response records are there which I am interested in while in the .warc generated by controlChromeHeadless, most of the response records are the ones with 2xx status. Is there a way to store all requests/responses in the .warc file?

**Comment by N0taN3rd** [comment]
@maturban thank you for pointing this out !!!!
I started to handle that in lines 366-435 but did not finish and it is needing a fix.

My handling of it is admittedly poor as it is now. 
I was thinking about using a solution similar to how [WAIL](https://github.com/N0taN3rd/wail/blob/wail-electron/wail-twitter/archive/resource.js) 
addresses it but have not had the cycles yet to do so.

Brief example:
```js
 for (let {req, res} of iterateReqRes(pageReqs, pageRes)) {
   // we have a 3xx request, the response to 3xx is in in req (request) 
    if (req.redirectResponse) {
       console.log(req.request) // the initiating request
       console.log(req.redirectResponse) // the 3xx response in the request object
       console.log(res) // the response to the 3xx specified location,  containes the request headers for the 3xx specified location
       console.log('--------------')
  }
}
```

If you have a few cycles to spare before I can to fix it feel free :smiley:
