### ISSUE TITLE
controlChromeHeadless appends "\r\n" to the end of entities

### ISSUE THREAD

**Issue by maturban** [N0taN3rd/controlChromeHeadless#4]
I used controlChromeHeadless to download https://web.archive.org/web/20170705235143im_/http://www.cs.odu.edu/~maturban/images/MohamedAturban.jpg which generated this WARC file [processed.warc.zip](https://github.com/N0taN3rd/controlChromeHeadless/files/1205983/processed.warc.zip). One the other hand I used the Python library "requests" to download the same image and used "warcio" to generate this WARC file [raw.warc.zip](https://github.com/N0taN3rd/controlChromeHeadless/files/1205987/raw.warc.zip). 

Now, I generated a hash of each "entity" (i.e., reading the WARC records using "warcio"). The hashes should have been identical but I got different hashes. I tested curl, wget and all produced the same hash as Python's requests did: (i.e., "e323e50d5613eb26c45fbfb71643cdef8d0f7323d65037480f3f6495f883e1d8") while the hash of the entity produced by controlChromeHeadless is "1c5c1284ed541c609dd960a99d944adf9c1827b6b64b34139692fcda6b6ac0e8".

It seems that controlChromeHeadless appends "\r\n" to the end of the original entity.

**Comment by N0taN3rd** [comment]
@maturban have you tried using [SquidWarc](https://github.com/N0taN3rd/Squidwarc)? 
This repo is now unmaintained.
But WARCreate also does something similar **https://github.com/machawk1/warcreate/blob/2016rebase/js/warcGenerator.js** 

The [warc spec](http://bibnum.bnf.fr/WARC/WARC_ISO_28500_version1_latestdraft.pdf) has two CRLF after each content block
```
 warc-file = 1*warc-record
 warc-record = header CRLF
 block CRLF CRLF
 header = version warc-fields
 version = "WARC/1.0" CRLF
 warc-fields = *named-field CRLF
 block = *OCTET 
```
Unless I missunderstood the syntax of how they are to be created I think that is valid

**Comment by maturban** [comment]
I am using  SquidWarc now. I work around this issue by eliminating whitespace at the end of an entity.
